### ISSUE TITLE
Support docker-compose via localhost server

### ISSUE THREAD

**Issue by docktermj** [Senzing/senzing-rest-api#33]
**Is your feature request related to a problem? Please describe.**
Right now, the Swagger editor, http://editor.swagger.io, doesn't allow for a local host when trying a URI

**Describe the solution you'd like**
Add **servers:** to allow use on localhost.

**Comment by docktermj** [comment]
As a work around, a user can modify the YAML to point to their server.  Example:

From :
```yaml
servers:
  - url: http://localhost:{port}
    variables:
      port:
        default: '8250'
  - url: http://senzing-api.local
```

To:
```yaml
servers:
  - url: http://10.1.1.100:{port}
    variables:
      port:
        default: '8250'
  - url: http://senzing-api.local
```
